name: Release
on:
  push:
    branches:
      - main


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Run tests
      run: |
        source venv/bin/activate
        python manage.py test


    # - name: Release
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')

    # - name: Create tag and push
    #   if: success()
    #   run: |
    #     git config --local user.name "GitHub Actions"
    - name: Set version number
      env:
        VERSION_NUMBER: 1.0.0
    
    - name: Set version number
      run: echo "export VERSION_NUMBER=1.0.0" >> $GITHUB_ENV



    - name: Get version number
      run: echo ::set-env name=VERSION_NUMBER::$(python -c "import semantic_release; print(semantic_release.get_version())" )

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION_NUMBER }}
        release_name: Release ${{ env.VERSION_NUMBER }}
        draft: false
        prerelease: false