name: Release
on:
  push:
    branches:
      - main


jobs:
  release:
  

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Run tests
      run: |
        source venv/bin/activate
        python manage.py test


    # - name: Release
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')

    - name: Release
      run: |
        source venv/bin/activate
        pip install python-semantic-release
    
    - name: Semantic-release
      run: |
        source venv/bin/activate
        semantic-release

    - name: Create tag and push
      if: success()
      run: |
        git config --local user.name "GitHub Actions"
    

    # - name: Create Release
    #   id: create_release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     draft: false
    #     prerelease: false



